### PR TITLE
Create trips list page with connect to api and fix bugs #30 #31

### LINKED ISSUE #8: [UI] Create ui for a trips page with search form and list of trips
**Branch name:** _feature/trip-list-ui_

### LINKED ISSUE #12: [FUNC] Connect trip list to api
**Branch:** _feature/trip-list-connect_

### LINKED ISSUE #30: Can't login on fresh install
Screenshot_1

Error occurred on first run

### LINKED ISSUE #31: Call sign in action when press submit button on keyboard
image

### PR DESCRIPTION
**Pull request by taruuuch**
Close #8 
Close #12 
Fix #31 
Fix #30

### CODE REVIEW

File: lib/pages/trips/widgets/trips_list.dart [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+  @override
+  Widget build(BuildContext context) {
+    final TripsBloc _bloc = Provider.of<TripsBloc>(context);
+    _bloc.dispatch(LoadTrips());
+    return new Container(
+      child: new StreamBuilder(
+        stream: _bloc.state,
+        builder: (context, AsyncSnapshot<TripsState> snapshot) {
+          if (snapshot.hasData) {
+            if (snapshot.data.trips != []) {
```
Comment (stenvix) [inline lib/pages/trips/widgets/trips_list.dart]: Please, use IsNotEmpty instead

File: lib/pages/trips/widgets/trips_list.dart [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+                      style: TextStyle(
+                        decoration: TextDecoration.underline
+                      ),  
+                    ),
+                  ),
+                ],
+              );
+            }
+          } else {
+            return null;
```
Comment (stenvix) [inline lib/pages/trips/widgets/trips_list.dart]: You can't return null, use SizedBox.shrink() instead

File: lib/pages/trips/widgets/trips_search.dart [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+              ),
+            ),
+            Expanded(
+              child: new CustomFlatButton(
+                onPressed: () => {
+                  DatePicker.showDatePicker(
+                    context,
+                    showTitleActions: true,
+                    minTime: DateTime(2018, 3, 5),
+                    maxTime: DateTime.now(),
```
Comment (stenvix) [inline lib/pages/trips/widgets/trips_search.dart]: Set max date in future

**Review by stenvix — CHANGES_REQUESTED** [review]
Fix and good to go
